name: Python application

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run unit tests with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history for accurate coverage reporting

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Install testing and coverage tools

      - name: Run tests
        # Run only the file: test_myfile.py
        env:
          PYTHONPATH: ./homework_1
        run: pytest --cov=homework_1/test/test_myfile.py

      - name: Upload results to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          