name: Python application

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.13'  

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#         pip install coverage  

#     - name: Run tests with coverage
#       run: |
#         coverage run -m pytest  
#         coverage report          
#         coverage xml             
      

#     - name: Upload coverage report to Codecov
#       uses: codecov/codecov-action@v3
#       with:
#         file: coverage.xml      
#         token: ${{ secrets.CODECOV_TOKEN }}
#         fail_ci_if_error: true  

#     - name: Upload test results to Codecov
#       if: ${{ !cancelled() }}
#       uses: codecov/test-results-action@v1
#       with:
#           token: ${{ secrets.CODECOV_TOKEN }}

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest 
        run: |
          coverage run -m pytest test/
    
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
